name: Docker Build and Push 

on:
  push:
    branches: [ master ]
  
jobs:
  Docker_Build_Push:
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker image Build and Push to Docker Hub
        uses: docker/build-push-action@v2.9.0
        with:
           # Path where code and Dockerfile is located
           context: /home/ubuntu/example
           tags: ${{ env:GITHUB_REPOSITORY }}:latest
           push: true
           
