name: hello-world
on: push
jobs:
  firstjob:
     runs-on: self-hosted
     steps:
         - name: Printing my name
           run: echo ${{env.GITHUB_REPOSITORY}}
           
           
           

