name: hello-world
on: push

jobs:
  firstjob:
     runs-on: self-hosted
     steps:
         - name: Printing my name
           run: echo "Hi Niranjan, Welcome to GitHub Actions"
         - name: Print GitHub Repository
           run:  echo $GITHUB_REPOSITORY
         - name: Print GitHub Workspace
           run:  echo ${{github.workspace}}
         - name: Print GitHub Runner Name
           run:  echo ${{github.runner.name}}
         - name: Print GitHub Event Name
           run:  echo ${{github.event.name}}
           
           
           
           

