name: hello-world
on: push
jobs:
  firstjob:
     runs-on: self-hosted
     steps:
         - name: Printing my name
           run: echo "Hi Niranjan, Welcome to GitHub Actions"
           run: echo $GITHUB_REPOSITORY
           
           

