name: hello-world
on: push
jobs:
  firstjob:
     runs-on: self-hosted
     steps:
         - name: Printing my name
           run: echo "Hi Niranjan, Welcome to GitHub Actions"
         - name: Print the GitHub repository used
           run:  echo ${{github.repository}}
           
           
           

