name: hello-world
on: push

jobs:
  firstjob:
     runs-on: self-hosted
     steps:
         - name: Printing my name
           run: echo "Hi Niranjan, Welcome to GitHub Actions"
         - name: Print GitHub Repository
           run:  echo $env:GITHUB_REPOSITORY
         - name: Print GitHub Workspace
           run:  echo $env:GITHUB_WORKSPACE
         - name: Print GitHub Runner Name
           run:  echo $env:GITHUB_RUNNER_NAME
         - name: Print GitHub Event Name
           run:  echo $env:GITHUB_EVENT_NAME
           
           
           
           

