name: CI with Maven

on:
  push:
    branches: [ master ]
  
jobs:
  Maven_Build_Deploy:
    runs-on: self-hosted
    steps:
         - uses: actions/checkout@v2
         - name: Build with Maven
           run: mvn clean install
    
       
