name: CI with Maven

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn clean install
    - name: Deploy to Tomcat
      run: copy ${env:GITHUB_WORKSPACE}\HW-Maven-Repo\target\HelloWorld-Maven.war E:\apache-tomcat-7.0.65\apache-tomcat-7.0.65\webapps\
      
