name: CI with Maven

on:
  push:
    branches: [ master ]
  
jobs:
  Maven_Build_Deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn clean install
    
    - name: Upload a Build Artifact 
      uses: actions/upload-artifact@v2.3.1
      with:
           name: assets-for-upload
           path: target/*.war
           retention-days: 5
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
           name: Download a Build Artifact
           # Destination path
           path: e:\temp\rel
    
    - name: Create Release
    - uses: ncipollo/release-action@v1.9.0
      with:
        artifacts: "release_v1.zip,target/*.war"
        
    - name: Deploy to Tomcat
      run: copy ${env:GITHUB_WORKSPACE}\target\HelloWorld-Maven.war E:\apache-tomcat-7.0.65\apache-tomcat-7.0.65\webapps\
      
