name: Github Secret Example

on:
  push:
    branches: [ master ]
  
jobs:
  Docker_Login_Check:
    runs-on: self-hosted
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
