name: Github Secret Example

on:
  push:
    branches: [ master ]
  
jobs:
  Docker_Login_Check:
    runs-on: self-hosted
    steps: 
      - run: sudo su
      - run: |
          usermod -aG docker ubuntu
          docker login -u vniranjan1972 -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker ps -a
